# -*- coding: utf-8 -*-
"""dataset1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cs-EB9q_BacAJ1algPzaSNAkFC9dC-QS

FIX (this version):
    The original script removed BOTH IP addresses and ports when building
    the "without shortcut features" dataset. That conflates two different
    hypotheses (IP memorization vs. port shortcut learning). This version
    only removes port features (id.orig_p, id.resp_p) and KEEPS the IP
    address features (id.orig_h, id.resp_h) in both configurations.
"""

import pandas as pd
import numpy as np
import os
from lightgbm import LGBMClassifier
# Provide a notebook-style `display` when running as a script
try:
    from IPython.display import display
except Exception:
    def display(x):
        try:
            # for DataFrame-like objects, show head
            print(x.head())
        except Exception:
            print(x)

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.pipeline import Pipeline

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.model_selection import cross_val_score


from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
# ==========================================
# LOAD DATASET
# ==========================================

column_names = [
    "ts",
    "uid",
    "id.orig_h",
    "id.orig_p",
    "id.resp_h",
    "id.resp_p",
    "proto",
    "service",
    "duration",
    "orig_bytes",
    "resp_bytes",
    "conn_state",
    "local_orig",
    "local_resp",
    "missed_bytes",
    "history",
    "orig_pkts",
    "orig_ip_bytes",
    "resp_pkts",
    "resp_ip_bytes",
    "tunnel_parents",
    "Label",
    "extra_column"      # remove later if empty
]

# Resolve dataset path relative to this script so it runs outside Colab
script_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(script_dir, "netsec.csv")

df = pd.read_csv(
    csv_path,
    sep="\t",
    header=None,
    names=column_names,
    comment="#",
    engine="python"
)

# ==========================================
# DATASET INFORMATION
# ==========================================

print(df.shape)

display(df.head())

print(df.columns.tolist())

# ==========================================
# REMOVE EMPTY COLUMN
# ==========================================

if "extra_column" in df.columns:
    if df["extra_column"].isnull().all():
        df.drop(columns=["extra_column"], inplace=True)

# ==========================================
# CHECK DUPLICATES
# ==========================================

duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)
print("Percentage :", duplicates / len(df) * 100)

# Remove duplicate rows
df = df.drop_duplicates().reset_index(drop=True)

print("Dataset after removing duplicates:", df.shape)

# ==========================================
# SELECT FEATURES
# ==========================================

selected_features = [

    "id.orig_p",
    "id.resp_p",

    "id.orig_h",
    "id.resp_h",

    "proto",
    "service",

    "duration",

    "orig_bytes",
    "resp_bytes",

    "conn_state",

    "missed_bytes",

    "orig_pkts",
    "orig_ip_bytes",

    "resp_pkts",
    "resp_ip_bytes",

    "Label"

]

df = df[selected_features]

# Replace placeholder '-' with NaN and coerce numeric columns to numeric dtype
# Replace placeholder '-' (possibly with surrounding spaces) with NaN
df.replace(to_replace=r"^\s*-\s*$", value=np.nan, regex=True, inplace=True)

# Define categorical columns early so we can treat them separately
categorical_columns = [
    "proto",
    "service",
    "conn_state"
]

# Fill missing categorical values with a token, coerce the rest to numeric
df[categorical_columns] = df[categorical_columns].fillna("missing")

numeric_cols = [c for c in df.columns if c not in categorical_columns + ['Label']]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# ==========================================
# ENCODE CATEGORICAL FEATURES
# ==========================================

categorical_columns = [

    "proto",
    "service",
    "conn_state"

]

encoder = LabelEncoder()

for col in categorical_columns:

    df[col] = encoder.fit_transform(
        df[col].astype(str)
    )

# ==========================================
# ENCODE IP ADDRESS FEATURES
# ==========================================

ip_columns = [
    "id.orig_h",
    "id.resp_h"
]

for col in ip_columns:
    df[col] = encoder.fit_transform(
        df[col].astype(str)
    )
    
# ==========================================
# ENCODE LABELS
# ==========================================

label_encoder = LabelEncoder()

df["Label"] = label_encoder.fit_transform(
    df["Label"]
)

# ==========================================
# FEATURE CORRELATION
# ==========================================

correlation = df.corr(numeric_only=True)["Label"]

print(correlation.sort_values(ascending=False))

# ==========================================
# CREATE DATASETS
# ==========================================

# All features (IPs + Ports + behavioral features)
X_full = df.drop(columns=["Label"])

# Remove ONLY the port features. IP address features are intentionally kept
# so this comparison isolates port dependency specifically, rather than
# mixing it with IP-address memorization.
X_no_port = df.drop(
    columns=[
        "id.orig_p",
        "id.resp_p",
        "Label"
    ]
)

y = df["Label"]

print("FULL DATASET :", X_full.shape)
print("WITHOUT PORTS (IPs kept) :", X_no_port.shape)
print("Labels :", y.shape)

# ==========================================
# MACHINE LEARNING MODELS
# ==========================================

models = {

    "Logistic Regression":
    Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=1000))
    ]),

    "Decision Tree":
    DecisionTreeClassifier(
        random_state=42
    ),

    "Random Forest":
    RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),

    "SVM":
    Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC())
    ]),

    "KNN":
    Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier())
    ]),

    "XGBoost":
    XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    ),

    "LightGBM":
    LGBMClassifier(
        random_state=42,
        verbosity=-1
    )

}

# ==========================================
# MODEL EVALUATION FUNCTION
# ==========================================

def evaluate_models(X, y):

    # Replace Inf with NaN
    X = X.replace([np.inf, -np.inf], np.nan)

    # Remove rows containing NaN (single pass - the duplicated
    # concat/dropna from the original script has been removed)
    combined = pd.concat([X, y], axis=1)

    print("\nMissing values in each column:")
    print(combined.isna().sum())

    combined = combined.dropna()

    X = combined.drop(columns=["Label"])
    y = combined["Label"]

    # -----------------------------
    # Train / Validation Split
    # -----------------------------
    print("Rows before split:", len(X))
    print("Labels before split:", len(y))

    X_train, X_test, y_train, y_test = train_test_split(

        X,
        y,

        test_size=0.20,

        random_state=42,

        stratify=y

    )

    print("="*50)
    print("Training Samples :", len(X_train))
    print("Validation Samples :", len(X_test))

    print("=" * 50)
    results = []

    # -----------------------------
    # Train Every Model
    # -----------------------------

    for name, model in models.items():

        print("Training :", name)

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        results.append({

            "Model": name,

            "Accuracy":
            accuracy_score(y_test, y_pred),

            "Precision":
            precision_score(
                y_test,
                y_pred,
                average="weighted",
                zero_division=0
            ),

            "Recall":
            recall_score(
                y_test,
                y_pred,
                average="weighted",
                zero_division=0
            ),

            "F1 Score":
            f1_score(
                y_test,
                y_pred,
                average="weighted",
                zero_division=0
            )

        })

    return pd.DataFrame(results)

# ==========================================
# TRAIN WITH PORT FEATURES
# ==========================================

results_full = evaluate_models(
    X_full,
    y
)

print(results_full)

# ==========================================
# TRAIN WITHOUT PORT FEATURES (IPs kept)
# ==========================================

results_no_port = evaluate_models(
    X_no_port,
    y
)

print(results_no_port)

# ==========================================
# COMPARE RESULTS
# ==========================================

comparison = results_full.merge(
    results_no_port,
    on="Model",
    suffixes=(" (Full)", " (No Ports)")
)

comparison = comparison.round(4)

display(comparison)

# ==========================================
# PERFORMANCE DROP
# ==========================================

comparison["Accuracy Drop"] = (
    comparison["Accuracy (Full)"] -
    comparison["Accuracy (No Ports)"]
)

comparison["Precision Drop"] = (
    comparison["Precision (Full)"] -
    comparison["Precision (No Ports)"]
)

comparison["Recall Drop"] = (
    comparison["Recall (Full)"] -
    comparison["Recall (No Ports)"]
)

comparison["F1 Drop"] = (
    comparison["F1 Score (Full)"] -
    comparison["F1 Score (No Ports)"]
)

comparison = comparison.round(4)

print("\n========== FINAL COMPARISON ==========\n")

display(comparison)

# ==========================================
# SAVE RESULTS
# ==========================================

comparison.to_csv(
    "Model_Comparison.csv",
    index=False
)

print("Results saved as Model_Comparison.csv")

# ==========================================
# 5-FOLD CROSS VALIDATION
# ==========================================

print("\n========== CROSS VALIDATION ==========\n")

cv_results = []

# Prepare data for cross-validation by removing rows with missing values
combined_cv = pd.concat([X_full, y], axis=1).dropna()
X_cv = combined_cv.drop(columns=["Label"]) if "Label" in combined_cv.columns else combined_cv.drop(columns=[y.name])
y_cv = combined_cv["Label"] if "Label" in combined_cv.columns else combined_cv[y.name]

for name, model in models.items():

    print("Running :", name)

    scores = cross_val_score(
        model,
        X_cv,
        y_cv,
        cv=5,
        scoring="f1_weighted"
    )

    print("Scores :", scores)
    print("Average :", scores.mean())
    print()

    cv_results.append({

        "Model": name,

        "CV Mean F1": scores.mean(),

        "CV Std": scores.std()

    })

cv_results = pd.DataFrame(cv_results)

display(cv_results)

# ==========================================
# SAVE CROSS VALIDATION
# ==========================================

cv_results.to_csv(
    "CrossValidationResults.csv",
    index=False
)

print("Cross-validation results saved for dataset 1.")

# ==========================================
# FINAL SUMMARY
# ==========================================

print("="*60)
print("SUMMARY")
print("="*60)

print("\nDataset Size :", len(df))
print("Number of Features (With Ports) :", X_full.shape[1])
print("Number of Features (Without Ports, IPs kept) :", X_no_port.shape[1])

print("\nDuplicate Rows :", duplicates)

print("\nModel Comparison")

display(comparison)

print("\nCross Validation")

display(cv_results)

print("\nExperiment Completed Successfully")


# ==========================================
# EXPORT ALL RESULTS TO PDF
# ==========================================
styles = getSampleStyleSheet()

pdf = SimpleDocTemplate("Experiment_Results.pdf")

elements = []

# Title
elements.append(Paragraph("<b>Network Intrusion Detection Experiment Results</b>", styles["Title"]))
elements.append(Paragraph("<br/>", styles["Normal"]))

# Dataset Information
elements.append(Paragraph("<b>Dataset Information</b>", styles["Heading2"]))
elements.append(Paragraph(f"Dataset Size: {len(df)} rows", styles["Normal"]))
elements.append(Paragraph(f"Duplicate Rows: {duplicates}", styles["Normal"]))
elements.append(Paragraph(f"Features (Full): {X_full.shape[1]}", styles["Normal"]))
elements.append(Paragraph(f"Features (No Ports, IPs kept): {X_no_port.shape[1]}", styles["Normal"]))
elements.append(Paragraph("<br/>", styles["Normal"]))

# Helper function
def dataframe_to_table(dataframe, title):
    elements.append(Paragraph(f"<b>{title}</b>", styles["Heading2"]))

    data = [list(dataframe.columns)]
    data += dataframe.round(4).values.tolist()

    table = Table(data)

    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.grey),
        ("TEXTCOLOR", (0,0), (-1,0), colors.whitesmoke),

        ("GRID", (0,0), (-1,-1), 0.5, colors.black),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0,0), (-1,0), 8),

        ("ALIGN", (0,0), (-1,-1), "CENTER"),
    ]))

    elements.append(table)
    elements.append(Paragraph("<br/>", styles["Normal"]))

# Model Results
dataframe_to_table(results_full, "Model Performance (Full Features)")

# No Port Results
dataframe_to_table(results_no_port, "Model Performance (Without Ports, IPs kept)")

# Comparison
dataframe_to_table(comparison, "Performance Comparison")

# Cross Validation
dataframe_to_table(cv_results, "5-Fold Cross Validation")

# Finish
pdf.build(elements)

print("PDF report saved as 'Experiment_Results.pdf'")